apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- rollout.yaml
- service-active.yaml
- service-preview.yaml
- namespace.yaml
namespace: nodejs
images:
- name: aks-k8s-rollouts
  newName: avik6028/aks-k8s-rollouts
  newTag: 7467334ef6408bfecd9465279775be6e5ba19042
